#!/bin/bash -el

# Copyright 2015 basebuilder authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

echo "Deploying the PHP application..."

APP_DIR=/home/application/current
SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/base/deploy

# Deploying
echo "Starting application configuration"
sudo -E python ${SOURCE_DIR}/php/deploy.py install
python ${SOURCE_DIR}/php/deploy.py environment
sudo mv /home/application/current/wp-content /shared/wp-content
sudo ln -sf /shared/wp-content /home/application/current/wp-content
sudo chown -R ubuntu:ubuntu /shared/wp-content
